/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.3.2.380
 * mbs - false 
 */  
package com.sofos.test.android.intrnl;

@SuppressWarnings("all")
public class ChangeLogImplMetaData extends com.sybase.reflection.EntityMetaDataEx
{
    /**
     * Sybase internal use only.
     */
    public ChangeLogImplMetaData()
    {
        super(com.sofos.test.android.AndroidMobileAppTestDB.getMetaData());
        _init();
    }
    protected void _init()
    {
        setId(0);
        setAttributes(new com.sybase.reflection.AttributeMetaDataList());
        setAttributeMap(new com.sybase.reflection.AttributeMap());
        com.sybase.reflection.AttributeMetaData operationType_attribute = addAttributeWithParams
        	(235, "operationType", "char", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"c\"", "char(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData rootEntityType_attribute = addAttributeWithParams
        	(236, "rootEntityType", "int", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"d\"", "integer", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData rootSurrogateKey_attribute = addAttributeWithParams
        	(237, "rootSurrogateKey", "long", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"e\"", "bigint", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData entityType_attribute = addAttributeWithParams
        	(233, "entityType", "int", 
        	-1, 
        	false, true, false, false, false, 
        	false,false, 
        	"\"a\"", "integer", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData surrogateKey_attribute = addAttributeWithParams
        	(234, "surrogateKey", "long", 
        	-1, 
        	false, true, false, false, false, 
        	false,false, 
        	"\"b\"", "bigint", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        initAttributeMapFromAttributes();
        setName("ChangeLogImpl");
        setTable("\"androidmobileapptest_1_0_changelogimpl\"");
        setSynchronizationGroup("default");
        this.getKeyAttributes().add((entityType_attribute));
        this.getKeyAttributes().add((surrogateKey_attribute));
        this.setKeyClass("ChangeLogKey");
    }
    
    /**
     * Sybase internal use only.
     */
    public  boolean isEntity()
    {
        return true;
    }
    
    /**
     * Sybase internal use only.
     */
    public  boolean isService()
    {
        return false;
    }
}