/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.3.2.380
 * mbs - false 
 */  
package com.sofos.test.android.intrnl;

@SuppressWarnings("all")
public class CustomerMetaData extends com.sybase.reflection.EntityMetaDataEx
{
    /**
     * Sybase internal use only.
     */
    public CustomerMetaData()
    {
        super(com.sofos.test.android.AndroidMobileAppTestDB.getMetaData());
        _init();
    }
    protected void _init()
    {
        setId(1);
        setAttributes(new com.sybase.reflection.AttributeMetaDataList());
        setAttributeMap(new com.sybase.reflection.AttributeMap());
        com.sybase.reflection.AttributeMetaData ID_attribute = addAttributeWithParams
        	(53, "ID", "string", 
        	10, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"a\"", "varchar(40)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData FNAME_attribute = addAttributeWithParams
        	(54, "FNAME", "string", 
        	35, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"b\"", "varchar(140)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData LNAME_attribute = addAttributeWithParams
        	(55, "LNAME", "string", 
        	35, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"c\"", "varchar(140)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData ADDRESS_attribute = addAttributeWithParams
        	(56, "ADDRESS", "string", 
        	35, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"d\"", "varchar(140)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CITY_attribute = addAttributeWithParams
        	(57, "CITY", "string", 
        	35, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"e\"", "varchar(140)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData STATE_attribute = addAttributeWithParams
        	(58, "STATE", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"f\"", "varchar(12)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData ZIP_attribute = addAttributeWithParams
        	(59, "ZIP", "string", 
        	10, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"g\"", "varchar(40)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PHONE_attribute = addAttributeWithParams
        	(60, "PHONE", "string", 
        	16, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"h\"", "varchar(64)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData COMPANY_NAME_attribute = addAttributeWithParams
        	(61, "COMPANY_NAME", "string", 
        	25, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"i\"", "varchar(100)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData surrogateKey_attribute = addAttributeWithParams
        	(62, "surrogateKey", "long", 
        	-1, 
        	false, true, false, false, false, 
        	false,false, 
        	"\"j\"", "bigint", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.GLOBAL,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        initAttributeMapFromAttributes();
        setName("Customer");
        setTable("\"androidmobileapptest_1_0_customer\"");
        setSynchronizationGroup("default");
        com.sybase.reflection.IndexMetaData findByPrimaryKeyIndex_index = new com.sybase.reflection.IndexMetaData();
        findByPrimaryKeyIndex_index.setName("findByPrimaryKeyIndex");
        findByPrimaryKeyIndex_index.getAttributes().add(ID_attribute);
        this.getIndice().add(findByPrimaryKeyIndex_index);
        this.getKeyAttributes().add((surrogateKey_attribute));
    }
    
    /**
     * Sybase internal use only.
     */
    public  boolean isEntity()
    {
        return true;
    }
    
    /**
     * Sybase internal use only.
     */
    public  boolean isService()
    {
        return false;
    }
}