/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.3.2.380
 * mbs - false 
 */
package com.sofos.test.android.intrnl;

@SuppressWarnings("all")
public  class SISSubscriptionKey extends com.sybase.sup.client.persistence.SISSubscriptionKey implements com.sybase.reflection.ClassWithMetaData
{
    private static com.sofos.test.android.intrnl.SISSubscriptionKeyMetaData META_DATA = new com.sofos.test.android.intrnl.SISSubscriptionKeyMetaData();
    
    /**
     * Return MetaData instance.  
     */
    public com.sybase.reflection.ClassMetaData getClassMetaData()
    {
        return META_DATA;
    }
    
    /**
     * Return MetaData instance.  
     */
    public static com.sybase.reflection.ClassMetaData getMetaData()
    {
        return META_DATA;
    }
    protected static com.sybase.sup.client.persistence.ClassDelegate DELEGATE = 
        new com.sybase.sup.client.persistence.ClassDelegate("SISSubscriptionKey", com.sofos.test.android.intrnl.SISSubscriptionKey.class, META_DATA, com.sofos.test.android.AndroidMobileAppTestDB.getDelegate());
}