package com.sofos.test.android;

/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.3.2.380
 * mbs - false 
 */
public abstract class EntityType
{
    public static int Customer = 1;
}