/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.3.2.380
 * mbs - false 
 */
package com.sofos.test.android;

@SuppressWarnings("all")
public  class KeyGenerator extends com.sybase.sup.client.persistence.RbsKeyGenerator implements com.sybase.reflection.ClassWithMetaData
{
    static
    {
        kgMap.put("androidmobileapptest:1.0", new com.sofos.test.android.KeyGenerator());
    }
    
    public KeyGenerator()
    {
        super(com.sofos.test.android.AndroidMobileAppTestDB.getDelegate(), "androidmobileapptest_1_0_keygenerator", 100000);
    }
    
    /** Begin code region: MetaData **/
    private static com.sofos.test.android.intrnl.KeyGeneratorMetaData META_DATA = new com.sofos.test.android.intrnl.KeyGeneratorMetaData();
    
    /**
     * return MetaData object  
     */
    public com.sybase.reflection.ClassMetaData getClassMetaData()
    {
        return META_DATA;
    }
    
    /**
     * return MetaData object  
     */
    public static com.sybase.reflection.EntityMetaData getMetaData()
    {
        return META_DATA;
    }
    
    /** End code region: MetaData **/
    
    protected static com.sybase.sup.client.persistence.EntityDelegate DELEGATE = 
        com.sybase.sup.client.persistence.DelegateFactory.createEntityDelegate("KeyGenerator", com.sofos.test.android.KeyGenerator.class, "AndroidMobileAppTest.KeyGenerator", META_DATA, com.sofos.test.android.AndroidMobileAppTestDB.getDelegate());
        
    /**
     * Generate surrogate key.  
     */
    public static long generateId()
    {
        return com.sofos.test.android.AndroidMobileAppTestDB.getDelegate().generateId();
    }
}