/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.3.2.380
 * mbs - false 
 */
package com.sofos.test.android;

@SuppressWarnings("all")
public  class PackageProperties extends com.sybase.persistence.AbstractEntity implements com.sybase.persistence.MobileBusinessObject, com.sybase.sup.client.persistence.AbstractPackageProperties, com.sybase.reflection.ClassWithMetaData
{
    /** Begin code region: MetaData **/
    private static com.sofos.test.android.intrnl.PackagePropertiesMetaData META_DATA = new com.sofos.test.android.intrnl.PackagePropertiesMetaData();
    
    /**
     * return MetaData object  
     */
    public com.sybase.reflection.ClassMetaData getClassMetaData()
    {
        return META_DATA;
    }
    
    /**
     * return MetaData object  
     */
    public static com.sybase.reflection.EntityMetaData getMetaData()
    {
        return META_DATA;
    }
    
    /** End code region: MetaData **/
    protected static com.sybase.sup.client.persistence.EntityDelegate DELEGATE = 
        com.sybase.sup.client.persistence.DelegateFactory.createEntityDelegate("PackageProperties", com.sofos.test.android.PackageProperties.class, "AndroidMobileAppTest.PackageProperties", META_DATA, com.sofos.test.android.AndroidMobileAppTestDB.getDelegate());
    
    
    /** Begin code region: Properties **/
    private java.lang.String __value ;  
    
      
    
      
    
      
    
      
    
    private java.lang.String __key ;  
    
      
    
      
    
    public java.lang.String getAttributeString(int id)
    {
        switch(id)
        {
        case 211:
            return getValue();
        case 210:
            return getKey();
        default:
            return super.getAttributeString(id);
        }
    }
    
    public void setAttributeString(int id, java.lang.String v)
    {
        switch(id)
        {
        case 211:
            setValue((java.lang.String)v);
            break;
        case 210:
            setKey((java.lang.String)v);
            break;
        default:
            super.setAttributeString(id, v);
            break;
        }
    }
    
    public Object getAttributeJson(int id)
    {
        switch(id)
        {
        default:
            return super.getAttributeJson(id);
        }
    }
    
    public void setAttributeJson(int id, Object value)
    {
        switch(id)
        {
        default:
            super.setAttributeJson(id, value);
            break;
        }
    }
    /** End code region: Properties **/
    
    /** Begin code region: Constructor and init **/
    /**
     * Creates an instance of com.sofos.test.android.PackageProperties  
     */
    public PackageProperties()
    {
        setEntityDelegate(DELEGATE);
        _init();
    }
    protected void _init()
    {
        
    }
    /** End code region: Constructor and init **/
    
    /**
     * Get the value of value  
     */
    public java.lang.String getValue()
    {
        
        return __value;
    }
    /**
     * Set the value of value  
     */
    public void setValue(java.lang.String value)
    {
        if ((__value == null) != (value == null) || (value != null && ! value.equals(__value)))
        {
            _isDirty = true;
        }
        __value = value;
    }       
    /**
     * Get the value of key  
     */
    public java.lang.String getKey()
    {
        
        return __key;
    }
    /**
     * Set the value of key  
     */
    public void setKey(java.lang.String value)
    {
        if ((__key == null) != (value == null) || (value != null && ! value.equals(__key)))
        {
            _isDirty = true;
        }
        __key = value;
    }
    
    /**
     * Search mobile business object using surrogateKey
     * @param id surrogateKey
     * @return mobile business object
     */
    public static com.sofos.test.android.PackageProperties find(java.lang.String id)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "PackageProperties.find()";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
            Object[] keys = new Object[]{id};
            return (com.sofos.test.android.PackageProperties)(DELEGATE.findEntityWithKeys(keys));
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    
    /**
     * Get the mobile business object by surrogate key.
     * @param id surrogate key
     * @return the mobile business object for the surroget key
     * @exception ObjectNotFoundException Thrown if unable to retrieve mobile business object.
     */
    public static com.sofos.test.android.PackageProperties load(java.lang.String id)
    {
        return (com.sofos.test.android.PackageProperties)(DELEGATE.load(id));
    }
    
    /**
     * Get surroget key of the mobile business object  
     */
    public java.lang.String _pk()
    {
        return (java.lang.String)i_pk();
    }
    
    /** Begin code region: Finder methods **/
    /**
     * return MBO count filter by query object  
     */
    public static int getSize(com.sybase.persistence.Query query)
    {
        return DELEGATE.getSize(query);
    }
    
    /**
     * Find a List of PackageProperties
     * @param query The query to be filter.
     * @exception PersistenceException Thrown if unable to retrieve mobile business object.
     */
    public static com.sybase.collections.GenericList<com.sofos.test.android.PackageProperties> findWithQuery(com.sybase.persistence.Query query)
    {
        return (com.sybase.collections.GenericList<com.sofos.test.android.PackageProperties>)(Object)DELEGATE.findWithQuery(query, com.sofos.test.android.PackageProperties.class);
    }
    
    
    
    
    /** End code region: Finder methods **/
    
    public com.sybase.collections.GenericList<com.sybase.persistence.LogRecord> getLogRecords()
    {
        return com.sofos.test.android.LogRecordImpl.findByEntity("PackageProperties", keyToString());
    }
    
    
    
    
    
    
    
    
    
    /**
     * Submit pending operations of the mobile business object (ready for sending to server)  
     */
    public static void submitPendingOperations()
    {
        DELEGATE.submitPendingOperations();
    }
    
    /**
     * Cancel all the pending operations (not submitted operation).  
     */
    public static void cancelPendingOperations()
    {
        DELEGATE.cancelPendingOperations();
    }
    /**
     * Get the last called operation of the mobile business object  
     */
    public String getLastOperation()
    {
        if (getPendingChange() == 'C')
        {
        }
        else if (getPendingChange() == 'D')
        {
        }
        else if (getPendingChange() == 'U')
        {
        }
        return null;
    }
    
    public com.sofos.test.android.PackageProperties getDownloadState()
    {
        return (com.sofos.test.android.PackageProperties)i_getDownloadState();
    }
    
    public com.sofos.test.android.PackageProperties getOriginalState()
    {
        return (com.sofos.test.android.PackageProperties)i_getOriginalState();
    }
}