/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.3.2.380
 * mbs - false 
 */
package com.sofos.test.android;

@SuppressWarnings("all")
public  class PersonalizationParameters extends com.sybase.sup.client.persistence.AbstractPersonalizationParameters implements com.sybase.reflection.ClassWithMetaData
{
    private static com.sofos.test.android.intrnl.PersonalizationParametersMetaData META_DATA = new com.sofos.test.android.intrnl.PersonalizationParametersMetaData();
    
    /**
     * Return MetaData instance.  
     */
    public com.sybase.reflection.ClassMetaData getClassMetaData()
    {
        return META_DATA;
    }
    
    /**
     * Return MetaData instance.  
     */
    public static com.sybase.reflection.ClassMetaData getMetaData()
    {
        return META_DATA;
    }
    protected static com.sybase.sup.client.persistence.ClassDelegate DELEGATE = 
        new com.sybase.sup.client.persistence.ClassDelegate("PersonalizationParameters", com.sofos.test.android.PersonalizationParameters.class, META_DATA, com.sofos.test.android.AndroidMobileAppTestDB.getDelegate());
    
    /**
     * Creates an instance of com.sofos.test.android.PersonalizationParameters  
     */
    public PersonalizationParameters()
    {
        this.setClassDelegate(DELEGATE);
        _init();
    }
    protected void _init()
    {
        
        clientPersonalizationTableName = "co_androidmobileapptest_1_0_clientpersonalization";
        load();
    }
    
    private java.lang.String __username ;  
    
    private boolean __usernameUserDefined  = com.sybase.afx.json.JsonValue.getBoolean("false");  
    
    private java.lang.String __password ;  
    
    private boolean __passwordUserDefined  = com.sybase.afx.json.JsonValue.getBoolean("false");  
    
    public java.lang.String getAttributeString(int id)
    {
        switch(id)
        {
        case 288:
            return getUsername();
        case 290:
            return getPassword();
        default:
            return super.getAttributeString(id);
        }
    }
    
    public void setAttributeString(int id, java.lang.String v)
    {
        switch(id)
        {
        case 288:
            setUsername((java.lang.String)v);
            break;
        case 290:
            setPassword((java.lang.String)v);
            break;
        default:
            super.setAttributeString(id, v);
            break;
        }
    }
    public boolean getAttributeBoolean(int id)
    {
        switch(id)
        {
        case 289:
            return getUsernameUserDefined();
        case 291:
            return getPasswordUserDefined();
        default:
            return super.getAttributeBoolean(id);
        }
    }
    
    public void setAttributeBoolean(int id, boolean v)
    {
        switch(id)
        {
        case 289:
            setUsernameUserDefined((boolean)v);
            break;
        case 291:
            setPasswordUserDefined((boolean)v);
            break;
        default:
            super.setAttributeBoolean(id, v);
            break;
        }
    }
    
    public Object getAttributeJson(int id)
    {
        switch(id)
        {
        default:
            return super.getAttributeJson(id);
        }
    }
    
    public void setAttributeJson(int id, Object value)
    {
        switch(id)
        {
        default:
            super.setAttributeJson(id, value);
            break;
        }
    }
    
    /**
     * get the value of username  
     */
    public java.lang.String getUsername()
    {
        
        return __username;
    }
    
    /**
     * Set the value of username  
     */
    public void setUsername(java.lang.String value)
    {
        __username = value;
        if ( __usernameUserDefined == false )
        {
            __usernameUserDefined = true;
        }
    }
    
    /**
     * get the value of usernameUserDefined  
     */
    public boolean getUsernameUserDefined()
    {
        
        return __usernameUserDefined;
    }
    
    /**
     * Set the value of usernameUserDefined  
     */
    private void setUsernameUserDefined(boolean value)
    {
        __usernameUserDefined = value;
    }
    
    /**
     * get the value of password  
     */
    public java.lang.String getPassword()
    {
        
        return __password;
    }
    
    /**
     * Set the value of password  
     */
    public void setPassword(java.lang.String value)
    {
        __password = value;
        if ( __passwordUserDefined == false )
        {
            __passwordUserDefined = true;
        }
    }
    
    /**
     * get the value of passwordUserDefined  
     */
    public boolean getPasswordUserDefined()
    {
        
        return __passwordUserDefined;
    }
    
    /**
     * Set the value of passwordUserDefined  
     */
    private void setPasswordUserDefined(boolean value)
    {
        __passwordUserDefined = value;
    }
    
    
    
    protected void reset()
    {
        super.reset();
    }
}